#!/bin/bash
awk '
BEGIN { in_faq = 0 }
/<\!-- ===================================================/ {
  if (getline next_line > 0 && next_line ~ /FAQ/) {
    in_faq = 1;
    print "          {/* ==================================================="
    print "              FAQ & COMMUNITY"
    print "          =================================================== */}"
    print "          <section className=\"py-20 bg-[#080808] border-t border-white/5\">"
    print "            <div className=\"max-w-4xl mx-auto px-5 lg:px-10\">"
    print "              <div className=\"text-center mb-10\">"
    print "                <p className=\"text-[8px] uppercase tracking-[0.5em] text-[#D4AF37] mb-3\">"
    print "                  FAQ"
    print "                </p>"
    print "                <h2 className=\"font-serif text-4xl italic\">"
    print "                  Frequently Asked Questions"
    print "                </h2>"
    print "                <p className=\"text-white/60 text-sm mt-4 max-w-xl mx-auto\">"
    print "                  Everything You Need to Know<br/>"
    print "                  Clear, transparent answers about our 22K gold purity, authentic craftsmanship, sizing recommendations, secure shipping, and returns."
    print "                </p>"
    print "              </div>"
    print ""
    print "              {/* Search Bar */}"
    print "              <div className=\"max-w-2xl mx-auto mb-10\">"
    print "                <div className=\"relative\">"
    print "                  <Search className=\"absolute left-4 top-1/2 -translate-y-1/2 text-white/40\" size={18} />"
    print "                  <input"
    print "                    type=\"text\""
    print "                    placeholder=\"Search frequently asked questions (e.g. shipping, returns)...\""
    print "                    value={faqSearch}"
    print "                    onChange={(e) => setFaqSearch(e.target.value)}"
    print "                    className=\"w-full bg-[#050505] border border-white/10 text-white text-sm py-4 pl-12 pr-4 focus:outline-none focus:border-[#D4AF37] transition\""
    print "                  />"
    print "                </div>"
    print "              </div>"
    print ""
    print "              {/* Categories */}"
    print "              <div className=\"flex flex-wrap justify-center gap-3 mb-10\">"
    print "                {faqCategories.map((cat) => ("
    print "                  <button"
    print "                    key={cat}"
    print "                    onClick={() => setFaqCategory(cat)}"
    print "                    className={`px-5 py-2 text-[10px] uppercase tracking-[0.15em] transition border ${"
    print "                      faqCategory === cat"
    print "                        ? \"bg-[#D4AF37] text-black border-[#D4AF37]\""
    print "                        : \"bg-transparent text-white/60 border-white/10 hover:border-white/30\""
    print "                    }`}"
    print "                  >"
    print "                    {cat}"
    print "                  </button>"
    print "                ))}"
    print "              </div>"
    print ""
    print "              {/* FAQ List */}"
    print "              <div className=\"space-y-4\">"
    print "                {filteredFaqs.length > 0 ? ("
    print "                  filteredFaqs.map((item, idx) => ("
    print "                    <div"
    print "                      key={idx}"
    print "                      className=\"border border-white/6 p-5 hover:border-white/10 transition\""
    print "                    >"
    print "                      <button"
    print "                        type=\"button\""
    print "                        onClick={() => toggleFaq(idx)}"
    print "                        className=\"w-full flex justify-between items-start text-left gap-4\""
    print "                        aria-expanded={openFaq === idx}"
    print "                      >"
    print "                        <div className=\"flex gap-4 items-start\">"
    print "                          <span className=\"text-[#D4AF37] text-xs font-serif italic mt-0.5\">"
    print "                            {String(idx + 1).padStart(2, \"0\")}"
    print "                          </span>"
    print "                          <span className=\"font-medium text-white text-sm sm:text-base\">"
    print "                            {item.q}"
    print "                          </span>"
    print "                        </div>"
    print "                        <span className=\"mt-1\">"
    print "                          <ArrowRight"
    print "                            size={16}"
    print "                            className={`text-[#D4AF37] transition-transform duration-300 ${"
    print "                              openFaq === idx ? \"rotate-90\" : \"rotate-0\""
    print "                            }`}"
    print "                          />"
    print "                        </span>"
    print "                      </button>"
    print "                      <div"
    print "                        className={`text-white/60 text-sm overflow-hidden transition-all duration-300 ${"
    print "                          openFaq === idx ? \"max-h-96 mt-4 opacity-100\" : \"max-h-0 opacity-0\""
    print "                        }`}"
    print "                      >"
    print "                        <div className=\"pl-8\">"
    print "                          {item.a}"
    print "                        </div>"
    print "                      </div>"
    print "                    </div>"
    print "                  ))"
    print "                ) : ("
    print "                  <div className=\"text-center py-10 text-white/50 text-sm\">"
    print "                    No questions found matching your search."
    print "                  </div>"
    print "                )}"
    print "              </div>"
    print ""
    print "              {/* Contact Support Block */}"
    print "              <div className=\"mt-20 border border-white/10 bg-[#050505] p-8 sm:p-12 text-center\">"
    print "                <h3 className=\"font-serif text-2xl mb-3 text-white\">Still have questions?</h3>"
    print "                <p className=\"text-white/60 text-sm max-w-lg mx-auto mb-8\">"
    print "                  Can'\''t find what you'\''re looking for? Our dedicated customer care team is here to assist you with any inquiries about our collections."
    print "                </p>"
    print "                <a href=\"/contact\" className=\"inline-flex items-center justify-center border border-[#D4AF37] text-[#D4AF37] px-8 py-3 text-[10px] uppercase tracking-[0.2em] hover:bg-[#D4AF37] hover:text-black transition\">"
    print "                  Contact Support"
    print "                </a>"
    print "                <p className=\"text-white/40 text-xs mt-4\">"
    print "                  +91 1800 227 604"
    print "                </p>"
    print "              </div>"
    print ""
    print "              {/* Newsletter Block */}"
    print "              <div className=\"mt-12 bg-gradient-to-br from-[#101010] to-[#050505] border border-white/10 p-8 sm:p-12 text-center\">"
    print "                <div className=\"w-12 h-12 mx-auto border border-[#D4AF37]/30 rotate-45 flex items-center justify-center mb-8\">"
    print "                  <Mail size={18} className=\"text-[#D4AF37] -rotate-45\" />"
    print "                </div>"
    print "                <h3 className=\"font-serif text-2xl sm:text-3xl italic mb-3 text-white\">Join Our Community</h3>"
    print "                <p className=\"text-white/60 text-sm max-w-lg mx-auto mb-8\">"
    print "                  Stay Updated on New Gold Jewellery Trends. Receive exclusive offers, styling tips, and early access to new collections."
    print "                </p>"
    print "                <form className=\"max-w-md mx-auto flex flex-col sm:flex-row gap-3\" onSubmit={(e) => e.preventDefault()}>"
    print "                  <input"
    print "                    type=\"email\""
    print "                    placeholder=\"Email Address\""
    print "                    className=\"flex-1 bg-transparent border border-white/20 text-white text-sm px-4 py-3 focus:outline-none focus:border-[#D4AF37] transition\""
    print "                    required"
    print "                  />"
    print "                  <button"
    print "                    type=\"submit\""
    print "                    className=\"bg-[#D4AF37] text-black px-8 py-3 text-[10px] uppercase tracking-[0.2em] font-semibold hover:bg-white transition\""
    print "                  >"
    print "                    Sign Up"
    print "                  </button>"
    print "                </form>"
    print "              </div>"
    print ""
    print "            </div>"
    print "          </section>"
    next
  } else {
    print $0
    print next_line
    next
  }
}
/<\!-- ===================================================/ {
  if (in_faq == 1) {
    if (getline next_line > 0 && next_line ~ /GOLD STRIP/) {
      in_faq = 0;
      print $0
      print next_line
      next
    }
  }
}
{
  if (in_faq == 0) print $0
}
' src/pages/Home.tsx > src/pages/Home.tsx.new && mv src/pages/Home.tsx.new src/pages/Home.tsx
